source "https://github.com/crspybits/Specs.git"
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

# "For [!] [Xcodeproj] Generated duplicate UUIDs:"
# install! 'cocoapods', :deterministic_uuids => false

target 'SMSyncServer_Example' do
  pod 'SMSyncServer', :path => '../'
end
